# Generated by Django 4.2.1 on 2023-08-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="discount",
            field=models.IntegerField(default=0),
        ),
    ]
