# Generated by Django 4.2.1 on 2023-08-12 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_author_image_of_author_alter_author_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="image_of_author",
            new_name="imagemak",
        ),
    ]
