# Generated by Django 4.2.1 on 2023-08-12 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_rename_discount_course_discounts_course_certificate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="discounts",
        ),
    ]
