# Generated by Django 4.2.1 on 2023-08-12 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0004_rename_image_of_author_author_imagemak"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="imagemak",
            new_name="image",
        ),
    ]
