# Generated by Django 4.2.1 on 2023-08-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0004_remove_course_discounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="discount",
            field=models.FloatField(default=0),
        ),
    ]
