# Generated by Django 4.2.1 on 2023-08-12 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0005_course_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="certificate",
        ),
    ]
