# Generated by Django 4.2.1 on 2023-08-13 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0005_rename_imagemak_author_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_of_unit",
                to="course.unit",
            ),
        ),
    ]
