# Generated by Django 4.2.1 on 2023-08-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0006_remove_course_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="certificate",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
    ]
