# Generated by Django 4.2.1 on 2023-08-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0007_alter_video_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(blank=True, upload_to="videos/"),
        ),
    ]
