# Generated by Django 4.2.1 on 2023-08-13 01:46

import apps.course.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0009_alter_video_resource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(
                blank=True,
                upload_to="videos/",
                validators=[apps.course.validators.validate_video],
            ),
        ),
    ]
