# Generated by Django 4.2.1 on 2023-08-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0012_alter_video_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="resource",
            field=models.ManyToManyField(null=True, to="course.resource"),
        ),
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(null=True, upload_to="videos/"),
        ),
    ]
