# Generated by Django 4.2.1 on 2023-08-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0015_alter_video_video_alter_video_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_url",
            field=models.URLField(blank=True, default=None),
        ),
    ]
