# Generated by Django 4.2.1 on 2023-08-13 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0016_alter_video_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos_of_unit",
                to="course.unit",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_url",
            field=models.URLField(blank=True),
        ),
    ]
