# Generated by Django 4.2.1 on 2023-08-13 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0017_alter_video_unit_alter_video_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course",
                to="course.course",
            ),
        ),
    ]
