# Generated by Django 4.2.1 on 2023-08-13 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0019_alter_unit_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentvideo",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_parent",
                to="course.commentvideo",
            ),
        ),
    ]
