# Generated by Django 4.2.1 on 2023-08-13 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0020_alter_commentvideo_parent_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentvideo",
            name="main_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_comments",
                to="course.commentvideo",
            ),
        ),
        migrations.AlterField(
            model_name="commentvideo",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_comments",
                to="course.commentvideo",
            ),
        ),
    ]
