# Generated by Django 4.2.4 on 2023-08-15 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='interview_videos/')),
                ('url', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='interview_thumbnails/')),
                ('description', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='accounts.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
